### ISSUE TITLE
Test with input n=0 is invalid

### ISSUE THREAD

**Issue by jalaka** [flofriday/UEB-Testsuite#2]
https://github.com/flofriday/UEB-Testsuite/blob/9c85a01a077008e4f4b82a44717c680d6e9509f6/2_asmb/test.c#L109

Reference implementation
```
void asmb(char x[], long n)
{
  long i,j;
  for (i=0,j=n-1; i<j; i++, j--) { <------- If n is zero then we have an infinte loop and will prbly seg fault
    char t=x[i];
    x[i]=x[j];
    x[j]=t;
  }
}
```

**Comment by flofriday** [comment]
I don't quite get your point.

If `n` is zero we get the following:
```
i = 0
j = n - 1 = -1
i < j = false
```

So the loop should never run and therefore nothing in the loop's body can cause a segfault.

Am I overseeing something here?

**Comment by jalaka** [comment]
Well my bad, I missread the condition. The test is valid and should be there.
