### ISSUE TITLE
Falscher Test Case?

### ISSUE THREAD

**Issue by jalaka** [flofriday/UEB-Testsuite#8]
https://github.com/flofriday/UEB-Testsuite/blob/cbab08587ced153f8073cb80c9789ae73b3e3698/ag/Coccho_49.0#L1-L3

Soweit ich das verstanden hab ist das ein Term vor dem @ Zeichen und kein Funktionsname. Daher müsste der Compiler Exit Code 3 ausgeben da das g in diesem Fall als undefinierte Variable interpretiert wird.

**Comment by flofriday** [comment]
Ja würd ich auch mal sagen. 
Ich vermute mal dass das noch übergeblieben ist weil die Tests von den letzten Aufgaben kopiert worden sind.
Ich werds mal ändern und den @Coccho fragen ob er/sie das auch so sieht.

**Comment by Jozott00** [comment]
Ja ich denk auch, dass der Testfall eigentlich exit 3 liefern sollte. Aus dem Forum:

```
Zunächst: Die zwei Stufen werden im Normalfall getrennt. Man ruft also die Funktion z.B. so auf:

var f=function{1,2,3};

// anderer code

return f@(4,5);
```
https://tuwel.tuwien.ac.at/mod/forum/discuss.php?d=313099

**Comment by flofriday** [comment]
Passt, ich hab jetzt den Testnamen geändert dass `exit(3)` erwartet wird.

**Comment by Coccho** [comment]
Entschuldigung, das habe ich total übersehen. Ja, stimmt, sollte mit Status 3 terminieren. Pingt mich ruhig nächstes Mal, hab den Kommentar gar nicht gesehen bis diesen Abend... xD
